title: YoFat的個人網站
description: 網路安全 × 人工智能 × 技術筆記
# 你的 GitHub Pages 網域（務必改成你的）
url: "https://yofat.github.io"
baseurl: ""

# 你的 GitHub repo（用於星星按鈕與 API）
github_owner: "yofat"           # ← 改成你的 GitHub 使用者名稱
github_repo: "yofat.github.io"  # ← 改成你的 repo 名稱

# 時區/語系
timezone: Asia/Taipei
lang: zh-TW

# Markdown 設定
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false  # 禁用 Rouge 行號
      start_line: 1
    default_lang: text
  gfm_quirks: paragraph_end

# 文章永久連結設定
permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# 確保 collections 在建置時被處理
collections_dir: ""

# 排除不需要處理的檔案和資料夾
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tools/
  - docs/
  - "*.backup"
  - "*_backup.*"
  - "*_new.*"

theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 分頁設定 - GitHub Pages 不支援 jekyll-paginate，已移除
# paginate: 10
# paginate_path: "/page:num/"

# SEO 設定
author:
  name: YoFat
  url: "https://yofat.github.io"

# 社交媒體
social:
  - name: GitHub
    url: "https://github.com/yofat"
  - name: Email  
    url: "mailto:your-email@example.com"

# 構建設定
safe: false
incremental: false
lsi: false